Does not compile with --enable-final.
The error was:

In file included from libkaddressbook_la.all_cpp.cpp:17:
/development/sources/kde-head/kdepim/kaddressbook/kabcore.cpp: In member
   function `void KABCore::save()':
/development/sources/kde-head/kdepim/kaddressbook/kabcore.cpp:650: warning: `
   save' is deprecated (declared at /opt/kde-cvs/include/kabc/stdaddressbook.h:
   86)
In file included from libkaddressbook_la.all_cpp.cpp:39:
/development/sources/kde-head/kdepim/kaddressbook/customfieldswidget.cpp: In
   function `void splitField(const QString&, QString&, QString&, QString&)':
/development/sources/kde-head/kdepim/kaddressbook/customfieldswidget.cpp:493: error: redefinition
   of `void splitField(const QString&, QString&, QString&, QString&)'
/development/sources/kde-head/kdepim/kaddressbook/advancedcustomfields.cpp:210: error: `
   void splitField(const QString&, QString&, QString&, QString&)' previously
   defined here
/development/sources/kde-head/kdepim/kaddressbook/customfieldswidget.cpp:493: error: redefinition
   of `void splitField(const QString&, QString&, QString&, QString&)'
/development/sources/kde-head/kdepim/kaddressbook/advancedcustomfields.cpp:210: error: `
   void splitField(const QString&, QString&, QString&, QString&)' previously
   defined here

svn path=/trunk/kdepim/; revision=292841