Compile with gcc-4.7, which is stricter.
../../libkcal/listbase.h:70:44: error: 'find' was not declared in
this scope, and no declarations were found by argument-dependent
lookup at the point of instantiation [-fpermissive]